### ISSUE TITLE
Cannot open: Is a directory

### ISSUE THREAD

**Issue by woody4165** [ricardobranco777/docker-volumes.sh#1] opened 2019-03-25 16:06 UTC
Hi

thanks for sharing your script.

I'm having trouble on using it, am I doing right?

`sudo ./docker-volumes.sh -v mynodered save nodered-copy.tar`

This is the container I'm trying to save

```
container-id        nodered/node-red-docker:v8                                "npm start -- --user…"   5 weeks ago         Up About an hour                             mynodered
```

I tried using name (mynodered) and container-id, with no success.

The error I get is

```
tar: //tmp.elTZ0QK1kg/nodered-copy.tar: Cannot open: Is a directory
tar: Error is not recoverable: exiting now
```

What can I do?

Thanks

**Comment by ricardobranco777** [comment] 2019-03-25 16:22
You found a bug in my script that I have now fixed. :)

With the full path there's no error.  You can either use the last version or pass the full path.

**Closed as completed by ricardobranco777** 2019-03-25 16:22 UTC

**Comment by kaaac** [comment] 2021-08-12 13:55
Hello!

Great tool!

I just succesfully migrated 2 stacks - but im stuck now with another one. 

I can't un-pack .tar file with volume. Below error:

`tar: root/.psono_server/settings.yaml: Cannot open: Is a directory`
`tar: Exiting with failure status due to previous errors`


Any idea?
Thanks

**Comment by ricardobranco777** [comment] 2021-08-12 13:57
> Hello!
> 
> Great tool!
> 
> I just succesfully migrated 2 stacks - but im stuck now with another one.
> 
> I can't un-pack .tar file with volume. Below error:
> 
> `tar: root/.psono_server/settings.yaml: Cannot open: Is a directory`
> `tar: Exiting with failure status due to previous errors`
> 
> Any idea?
> Thanks

Can you please post the full command line used?

**Comment by kaaac** [comment] 2021-08-12 14:09
Sure:
`
./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar
`

**Comment by ricardobranco777** [comment] 2021-08-12 14:31
> Sure:
> `./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar`

Are you running this command as root?  

Are you using the latest version of the script?

I guess I need a way to reproduce it.

**Comment by kaaac** [comment] 2021-08-12 14:56
- yes, im working as root at both systems.
- i think yes - script from here: https://github.com/ricardobranco777/docker-volumes.sh/blob/master/docker-volumes.sh

Contents of tar file (tar -tvf psono_alento_server_ee-volumes.tar):

`-rw-r--r-- root/root     17876 2020-03-31 01:25 root/.psono_server/settings.yaml`
`drwxr-xr-x root/root         0 2020-01-29 19:03 var/log/psono/`
`-rw-r--r-- root/root  96481625 2021-08-12 15:08 var/log/psono/audit.log`
`-rw-r--r-- root/root         0 2020-01-29 19:03 var/log/psono/query.log`

**Comment by ricardobranco777** [comment] 2021-08-12 15:10
> > Sure:
> > `./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar`
> 
> Are you running this command as root?
> 
> Are you using the latest version of the script?
> 
> I guess I need a way to reproduce it.



> Sure:
> `./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar`

Does it work using the whole path for the tarfile as this:
`./docker-volumes.sh psono_alento_server_ee load $PWD/psono_alento_server_ee-volumes.tar` ?

**Comment by kaaac** [comment] 2021-08-12 15:36
Unfortunately, the same error...

**Comment by ricardobranco777** [comment] 2021-08-12 15:41
> Unfortunately, the same error...

Please inspect the container for the `root/.psono_server/settings.yaml` file.  It looks like this file is mounted already as a directory.

In the options to create the docker container you must omit the ones that mount the volumes that are already in the tarfile.

If it continues failing, paste the output of `docker inspect psono_alento_server_ee` and 
 `bash -x ./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar`

**Comment by kaaac** [comment] 2021-08-12 16:31
I have no idea why docker is trying to treat the file as a directory. In fact, after creating the containers - in my case docker-compose create - the directory settings.yaml / is created 
This is my settings in docker-compose.yml:
``` 
  volumes:
      - /opt/docker/psono/alento/settings.yaml:/root/.psono_server/settings.yaml
```
and parts from docker inspect:

```
"HostConfig": {
            "Binds": [
                "/opt/docker/psono/alento/settings.yaml:/root/.psono_server/settings.yaml:rw",
                "/var/log/psono/alento:/var/log/psono:rw"
            ],

```

```
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/opt/docker/psono/alento/settings.yaml",
                "Destination": "/root/.psono_server/settings.yaml",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "bind",
                "Source": "/var/log/psono/alento",
                "Destination": "/var/log/psono",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],

```

Output from bash....:
```

  bash -x ./docker-volumes.sh psono_alento_server_ee load psono_alento_server_ee-volumes.tar
+ [[ psono_alento_server_ee == \-\v ]]
+ [[ psono_alento_server_ee == \-\-\v\e\r\b\o\s\e ]]
+ [[ 3 -ne 3 ]]
+ [[ ! load =~ ^(save|load)$ ]]
+ IMAGE=ubuntu:18.04
+ DOCKER=docker
+ CONTAINER=psono_alento_server_ee
++ readlink -f psono_alento_server_ee-volumes.tar
+ TAR_FILE=/root/psono_alento_server_ee-volumes.tar
+ set -e
+ case "$2" in
+ load_volumes
+ '[' '!' -f /root/psono_alento_server_ee-volumes.tar ']'
++ mktemp -du -p /
+ tmp_dir=/tmp.1JcK9VvC6f
+ docker run --rm --volumes-from psono_alento_server_ee -e LC_ALL=C.UTF-8 -v /root/psono_alento_server_ee-volumes.tar://tmp.1JcK9VvC6f/psono_alento_server_ee-volumes.tar:ro ubuntu:18.04 tar -xp -S -f //tmp.1JcK9VvC6f/psono_alento_server_ee-volumes.tar -C / --overwrite
tar: root/.psono_server/settings.yaml: Cannot open: Is a directory
tar: Exiting with failure status due to previous errors

```

A similar problem occurs with other containers from this stack and the other stack, similar one.

Do you suggest commenting out the lines for mounting problematic volumes before creating the containers from the target docker-compose.yml?
Then load the .tar using your script, then restore the commented lines, and then pick up the stack?

**Comment by ricardobranco777** [comment] 2021-08-12 19:19
> Do you suggest commenting out the lines for mounting problematic volumes before creating the containers from the target docker-compose.yml?
> Then load the .tar using your script, then restore the commented lines, and then pick up the stack?

That may work.

I haven't tested my script with Docker Compose since I no longer work with applications that store state in a way that can't be containerized.  Are you sure that you need my script at all?  Because I've seen people use it with Nginx, which is pointless.  When all data and state is stored in volumes, the whole stack can be recreated in other host without using this script.
